### YamlMime:ManagedReference
items:
- uid: PocoEmit.Configuration.PairTypeKey
  commentId: T:PocoEmit.Configuration.PairTypeKey
  id: PairTypeKey
  parent: PocoEmit.Configuration
  children:
  - PocoEmit.Configuration.PairTypeKey.#ctor(System.Type,System.Type)
  - PocoEmit.Configuration.PairTypeKey.Equals(PocoEmit.Configuration.PairTypeKey)
  - PocoEmit.Configuration.PairTypeKey.Equals(System.Object)
  - PocoEmit.Configuration.PairTypeKey.GetHashCode
  - PocoEmit.Configuration.PairTypeKey.LeftType
  - PocoEmit.Configuration.PairTypeKey.RightType
  langs:
  - csharp
  - vb
  name: PairTypeKey
  nameWithType: PairTypeKey
  fullName: PocoEmit.Configuration.PairTypeKey
  type: Class
  source:
    remote:
      path: PocoEmit/Configuration/MapTypeKey.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: PairTypeKey
    path: ../PocoEmit/Configuration/MapTypeKey.cs
    startLine: 16
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Configuration
  summary: 类型关联键
  example: []
  syntax:
    content: 'public class PairTypeKey : IEquatable<PairTypeKey>'
    content.vb: Public Class PairTypeKey Implements IEquatable(Of PairTypeKey)
  inheritance:
  - System.Object
  implements:
  - System.IEquatable{PocoEmit.Configuration.PairTypeKey}
- uid: PocoEmit.Configuration.PairTypeKey.#ctor(System.Type,System.Type)
  commentId: M:PocoEmit.Configuration.PairTypeKey.#ctor(System.Type,System.Type)
  id: '#ctor(System.Type,System.Type)'
  parent: PocoEmit.Configuration.PairTypeKey
  langs:
  - csharp
  - vb
  name: PairTypeKey(Type, Type)
  nameWithType: PairTypeKey.PairTypeKey(Type, Type)
  fullName: PocoEmit.Configuration.PairTypeKey.PairTypeKey(System.Type, System.Type)
  type: Constructor
  source:
    remote:
      path: PocoEmit/Configuration/MapTypeKey.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: .ctor
    path: ../PocoEmit/Configuration/MapTypeKey.cs
    startLine: 16
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Configuration
  summary: 类型关联键
  example: []
  syntax:
    content: public PairTypeKey(Type leftType, Type rightType)
    parameters:
    - id: leftType
      type: System.Type
      description: ''
    - id: rightType
      type: System.Type
      description: ''
    content.vb: Public Sub New(leftType As Type, rightType As Type)
  overload: PocoEmit.Configuration.PairTypeKey.#ctor*
  nameWithType.vb: PairTypeKey.New(Type, Type)
  fullName.vb: PocoEmit.Configuration.PairTypeKey.New(System.Type, System.Type)
  name.vb: New(Type, Type)
- uid: PocoEmit.Configuration.PairTypeKey.LeftType
  commentId: P:PocoEmit.Configuration.PairTypeKey.LeftType
  id: LeftType
  parent: PocoEmit.Configuration.PairTypeKey
  langs:
  - csharp
  - vb
  name: LeftType
  nameWithType: PairTypeKey.LeftType
  fullName: PocoEmit.Configuration.PairTypeKey.LeftType
  type: Property
  source:
    remote:
      path: PocoEmit/Configuration/MapTypeKey.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: LeftType
    path: ../PocoEmit/Configuration/MapTypeKey.cs
    startLine: 25
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Configuration
  summary: 映射源类型
  example: []
  syntax:
    content: public Type LeftType { get; }
    parameters: []
    return:
      type: System.Type
    content.vb: Public ReadOnly Property LeftType As Type
  overload: PocoEmit.Configuration.PairTypeKey.LeftType*
- uid: PocoEmit.Configuration.PairTypeKey.RightType
  commentId: P:PocoEmit.Configuration.PairTypeKey.RightType
  id: RightType
  parent: PocoEmit.Configuration.PairTypeKey
  langs:
  - csharp
  - vb
  name: RightType
  nameWithType: PairTypeKey.RightType
  fullName: PocoEmit.Configuration.PairTypeKey.RightType
  type: Property
  source:
    remote:
      path: PocoEmit/Configuration/MapTypeKey.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: RightType
    path: ../PocoEmit/Configuration/MapTypeKey.cs
    startLine: 30
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Configuration
  summary: 映射目标类型
  example: []
  syntax:
    content: public Type RightType { get; }
    parameters: []
    return:
      type: System.Type
    content.vb: Public ReadOnly Property RightType As Type
  overload: PocoEmit.Configuration.PairTypeKey.RightType*
- uid: PocoEmit.Configuration.PairTypeKey.GetHashCode
  commentId: M:PocoEmit.Configuration.PairTypeKey.GetHashCode
  id: GetHashCode
  parent: PocoEmit.Configuration.PairTypeKey
  langs:
  - csharp
  - vb
  name: GetHashCode()
  nameWithType: PairTypeKey.GetHashCode()
  fullName: PocoEmit.Configuration.PairTypeKey.GetHashCode()
  type: Method
  source:
    remote:
      path: PocoEmit/Configuration/MapTypeKey.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: GetHashCode
    path: ../PocoEmit/Configuration/MapTypeKey.cs
    startLine: 37
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Configuration
  summary: HashCode
  example: []
  syntax:
    content: public override int GetHashCode()
    return:
      type: System.Int32
      description: ''
    content.vb: Public Overrides Function GetHashCode() As Integer
  overridden: System.Object.GetHashCode
  overload: PocoEmit.Configuration.PairTypeKey.GetHashCode*
- uid: PocoEmit.Configuration.PairTypeKey.Equals(PocoEmit.Configuration.PairTypeKey)
  commentId: M:PocoEmit.Configuration.PairTypeKey.Equals(PocoEmit.Configuration.PairTypeKey)
  id: Equals(PocoEmit.Configuration.PairTypeKey)
  parent: PocoEmit.Configuration.PairTypeKey
  langs:
  - csharp
  - vb
  name: Equals(PairTypeKey)
  nameWithType: PairTypeKey.Equals(PairTypeKey)
  fullName: PocoEmit.Configuration.PairTypeKey.Equals(PocoEmit.Configuration.PairTypeKey)
  type: Method
  source:
    remote:
      path: PocoEmit/Configuration/MapTypeKey.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: Equals
    path: ../PocoEmit/Configuration/MapTypeKey.cs
    startLine: 49
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Configuration
  summary: 判同
  example: []
  syntax:
    content: public bool Equals(PairTypeKey other)
    parameters:
    - id: other
      type: PocoEmit.Configuration.PairTypeKey
      description: ''
    return:
      type: System.Boolean
      description: ''
    content.vb: Public Function Equals(other As PairTypeKey) As Boolean
  overload: PocoEmit.Configuration.PairTypeKey.Equals*
  implements:
  - System.IEquatable{PocoEmit.Configuration.PairTypeKey}.Equals(PocoEmit.Configuration.PairTypeKey)
- uid: PocoEmit.Configuration.PairTypeKey.Equals(System.Object)
  commentId: M:PocoEmit.Configuration.PairTypeKey.Equals(System.Object)
  id: Equals(System.Object)
  parent: PocoEmit.Configuration.PairTypeKey
  langs:
  - csharp
  - vb
  name: Equals(object)
  nameWithType: PairTypeKey.Equals(object)
  fullName: PocoEmit.Configuration.PairTypeKey.Equals(object)
  type: Method
  source:
    remote:
      path: PocoEmit/Configuration/MapTypeKey.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: Equals
    path: ../PocoEmit/Configuration/MapTypeKey.cs
    startLine: 56
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Configuration
  summary: 判同
  example: []
  syntax:
    content: public override bool Equals(object other)
    parameters:
    - id: other
      type: System.Object
      description: ''
    return:
      type: System.Boolean
      description: ''
    content.vb: Public Overrides Function Equals(other As Object) As Boolean
  overridden: System.Object.Equals(System.Object)
  overload: PocoEmit.Configuration.PairTypeKey.Equals*
  nameWithType.vb: PairTypeKey.Equals(Object)
  fullName.vb: PocoEmit.Configuration.PairTypeKey.Equals(Object)
  name.vb: Equals(Object)
references:
- uid: PocoEmit.Configuration
  commentId: N:PocoEmit.Configuration
  href: PocoEmit.html
  name: PocoEmit.Configuration
  nameWithType: PocoEmit.Configuration
  fullName: PocoEmit.Configuration
  spec.csharp:
  - uid: PocoEmit
    name: PocoEmit
    href: PocoEmit.html
  - name: .
  - uid: PocoEmit.Configuration
    name: Configuration
    href: PocoEmit.Configuration.html
  spec.vb:
  - uid: PocoEmit
    name: PocoEmit
    href: PocoEmit.html
  - name: .
  - uid: PocoEmit.Configuration
    name: Configuration
    href: PocoEmit.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.IEquatable{PocoEmit.Configuration.PairTypeKey}
  commentId: T:System.IEquatable{PocoEmit.Configuration.PairTypeKey}
  parent: System
  definition: System.IEquatable`1
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<PairTypeKey>
  nameWithType: IEquatable<PairTypeKey>
  fullName: System.IEquatable<PocoEmit.Configuration.PairTypeKey>
  nameWithType.vb: IEquatable(Of PairTypeKey)
  fullName.vb: System.IEquatable(Of PocoEmit.Configuration.PairTypeKey)
  name.vb: IEquatable(Of PairTypeKey)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - uid: PocoEmit.Configuration.PairTypeKey
    name: PairTypeKey
    href: PocoEmit.Configuration.PairTypeKey.html
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - uid: PocoEmit.Configuration.PairTypeKey
    name: PairTypeKey
    href: PocoEmit.Configuration.PairTypeKey.html
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: PocoEmit.Configuration.PairTypeKey.#ctor*
  commentId: Overload:PocoEmit.Configuration.PairTypeKey.#ctor
  href: PocoEmit.Configuration.PairTypeKey.html#PocoEmit_Configuration_PairTypeKey__ctor_System_Type_System_Type_
  name: PairTypeKey
  nameWithType: PairTypeKey.PairTypeKey
  fullName: PocoEmit.Configuration.PairTypeKey.PairTypeKey
  nameWithType.vb: PairTypeKey.New
  fullName.vb: PocoEmit.Configuration.PairTypeKey.New
  name.vb: New
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.type
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: PocoEmit.Configuration.PairTypeKey.LeftType*
  commentId: Overload:PocoEmit.Configuration.PairTypeKey.LeftType
  href: PocoEmit.Configuration.PairTypeKey.html#PocoEmit_Configuration_PairTypeKey_LeftType
  name: LeftType
  nameWithType: PairTypeKey.LeftType
  fullName: PocoEmit.Configuration.PairTypeKey.LeftType
- uid: PocoEmit.Configuration.PairTypeKey.RightType*
  commentId: Overload:PocoEmit.Configuration.PairTypeKey.RightType
  href: PocoEmit.Configuration.PairTypeKey.html#PocoEmit_Configuration_PairTypeKey_RightType
  name: RightType
  nameWithType: PairTypeKey.RightType
  fullName: PocoEmit.Configuration.PairTypeKey.RightType
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
- uid: PocoEmit.Configuration.PairTypeKey.GetHashCode*
  commentId: Overload:PocoEmit.Configuration.PairTypeKey.GetHashCode
  href: PocoEmit.Configuration.PairTypeKey.html#PocoEmit_Configuration_PairTypeKey_GetHashCode
  name: GetHashCode
  nameWithType: PairTypeKey.GetHashCode
  fullName: PocoEmit.Configuration.PairTypeKey.GetHashCode
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: PocoEmit.Configuration.PairTypeKey.Equals*
  commentId: Overload:PocoEmit.Configuration.PairTypeKey.Equals
  href: PocoEmit.Configuration.PairTypeKey.html#PocoEmit_Configuration_PairTypeKey_Equals_PocoEmit_Configuration_PairTypeKey_
  name: Equals
  nameWithType: PairTypeKey.Equals
  fullName: PocoEmit.Configuration.PairTypeKey.Equals
- uid: System.IEquatable{PocoEmit.Configuration.PairTypeKey}.Equals(PocoEmit.Configuration.PairTypeKey)
  commentId: M:System.IEquatable{PocoEmit.Configuration.PairTypeKey}.Equals(PocoEmit.Configuration.PairTypeKey)
  parent: System.IEquatable{PocoEmit.Configuration.PairTypeKey}
  definition: System.IEquatable`1.Equals(`0)
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1.equals
  name: Equals(PairTypeKey)
  nameWithType: IEquatable<PairTypeKey>.Equals(PairTypeKey)
  fullName: System.IEquatable<PocoEmit.Configuration.PairTypeKey>.Equals(PocoEmit.Configuration.PairTypeKey)
  nameWithType.vb: IEquatable(Of PairTypeKey).Equals(PairTypeKey)
  fullName.vb: System.IEquatable(Of PocoEmit.Configuration.PairTypeKey).Equals(PocoEmit.Configuration.PairTypeKey)
  spec.csharp:
  - uid: System.IEquatable{PocoEmit.Configuration.PairTypeKey}.Equals(PocoEmit.Configuration.PairTypeKey)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1.equals
  - name: (
  - uid: PocoEmit.Configuration.PairTypeKey
    name: PairTypeKey
    href: PocoEmit.Configuration.PairTypeKey.html
  - name: )
  spec.vb:
  - uid: System.IEquatable{PocoEmit.Configuration.PairTypeKey}.Equals(PocoEmit.Configuration.PairTypeKey)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1.equals
  - name: (
  - uid: PocoEmit.Configuration.PairTypeKey
    name: PairTypeKey
    href: PocoEmit.Configuration.PairTypeKey.html
  - name: )
- uid: PocoEmit.Configuration.PairTypeKey
  commentId: T:PocoEmit.Configuration.PairTypeKey
  parent: PocoEmit.Configuration
  href: PocoEmit.Configuration.PairTypeKey.html
  name: PairTypeKey
  nameWithType: PairTypeKey
  fullName: PocoEmit.Configuration.PairTypeKey
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System.IEquatable`1.Equals(`0)
  commentId: M:System.IEquatable`1.Equals(`0)
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1.equals
  name: Equals(T)
  nameWithType: IEquatable<T>.Equals(T)
  fullName: System.IEquatable<T>.Equals(T)
  nameWithType.vb: IEquatable(Of T).Equals(T)
  fullName.vb: System.IEquatable(Of T).Equals(T)
  spec.csharp:
  - uid: System.IEquatable`1.Equals(`0)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1.equals
  - name: (
  - name: T
  - name: )
  spec.vb:
  - uid: System.IEquatable`1.Equals(`0)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1.equals
  - name: (
  - name: T
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
