### YamlMime:ManagedReference
items:
- uid: PocoEmit.Configuration.ICompileInfo
  commentId: T:PocoEmit.Configuration.ICompileInfo
  id: ICompileInfo
  parent: PocoEmit.Configuration
  children:
  - PocoEmit.Configuration.ICompileInfo.Compiled
  langs:
  - csharp
  - vb
  name: ICompileInfo
  nameWithType: ICompileInfo
  fullName: PocoEmit.Configuration.ICompileInfo
  type: Interface
  source:
    remote:
      path: PocoEmit/Configuration/IEmitInfo.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: ICompileInfo
    path: ../PocoEmit/Configuration/IEmitInfo.cs
    startLine: 5
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Configuration
  summary: 编译信息
  example: []
  syntax:
    content: public interface ICompileInfo
    content.vb: Public Interface ICompileInfo
- uid: PocoEmit.Configuration.ICompileInfo.Compiled
  commentId: P:PocoEmit.Configuration.ICompileInfo.Compiled
  id: Compiled
  parent: PocoEmit.Configuration.ICompileInfo
  langs:
  - csharp
  - vb
  name: Compiled
  nameWithType: ICompileInfo.Compiled
  fullName: PocoEmit.Configuration.ICompileInfo.Compiled
  type: Property
  source:
    remote:
      path: PocoEmit/Configuration/IEmitInfo.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: Compiled
    path: ../PocoEmit/Configuration/IEmitInfo.cs
    startLine: 10
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Configuration
  summary: 是否已编译
  example: []
  syntax:
    content: bool Compiled { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property Compiled As Boolean
  overload: PocoEmit.Configuration.ICompileInfo.Compiled*
references:
- uid: PocoEmit.Configuration
  commentId: N:PocoEmit.Configuration
  href: PocoEmit.html
  name: PocoEmit.Configuration
  nameWithType: PocoEmit.Configuration
  fullName: PocoEmit.Configuration
  spec.csharp:
  - uid: PocoEmit
    name: PocoEmit
    href: PocoEmit.html
  - name: .
  - uid: PocoEmit.Configuration
    name: Configuration
    href: PocoEmit.Configuration.html
  spec.vb:
  - uid: PocoEmit
    name: PocoEmit
    href: PocoEmit.html
  - name: .
  - uid: PocoEmit.Configuration
    name: Configuration
    href: PocoEmit.Configuration.html
- uid: PocoEmit.Configuration.ICompileInfo.Compiled*
  commentId: Overload:PocoEmit.Configuration.ICompileInfo.Compiled
  href: PocoEmit.Configuration.ICompileInfo.html#PocoEmit_Configuration_ICompileInfo_Compiled
  name: Compiled
  nameWithType: ICompileInfo.Compiled
  fullName: PocoEmit.Configuration.ICompileInfo.Compiled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
