### YamlMime:ManagedReference
items:
- uid: PocoEmit.Collections.IConfigure`2
  commentId: T:PocoEmit.Collections.IConfigure`2
  id: IConfigure`2
  parent: PocoEmit.Collections
  children:
  - PocoEmit.Collections.IConfigure`2.Configure(`0,`1)
  langs:
  - csharp
  - vb
  name: IConfigure<TKey, TValue>
  nameWithType: IConfigure<TKey, TValue>
  fullName: PocoEmit.Collections.IConfigure<TKey, TValue>
  type: Interface
  source:
    remote:
      path: PocoEmit/Collections/IConfigure~2.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: IConfigure
    path: ../PocoEmit/Collections/IConfigure~2.cs
    startLine: 7
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Collections
  summary: 配置(用户行为)
  example: []
  syntax:
    content: public interface IConfigure<TKey, TValue>
    typeParameters:
    - id: TKey
      description: ''
    - id: TValue
      description: ''
    content.vb: Public Interface IConfigure(Of TKey, TValue)
  nameWithType.vb: IConfigure(Of TKey, TValue)
  fullName.vb: PocoEmit.Collections.IConfigure(Of TKey, TValue)
  name.vb: IConfigure(Of TKey, TValue)
- uid: PocoEmit.Collections.IConfigure`2.Configure(`0,`1)
  commentId: M:PocoEmit.Collections.IConfigure`2.Configure(`0,`1)
  id: Configure(`0,`1)
  parent: PocoEmit.Collections.IConfigure`2
  langs:
  - csharp
  - vb
  name: Configure(TKey, TValue)
  nameWithType: IConfigure<TKey, TValue>.Configure(TKey, TValue)
  fullName: PocoEmit.Collections.IConfigure<TKey, TValue>.Configure(TKey, TValue)
  type: Method
  source:
    remote:
      path: PocoEmit/Collections/IConfigure~2.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: Configure
    path: ../PocoEmit/Collections/IConfigure~2.cs
    startLine: 14
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Collections
  summary: 配置
  example: []
  syntax:
    content: void Configure(TKey key, TValue value)
    parameters:
    - id: key
      type: '{TKey}'
      description: ''
    - id: value
      type: '{TValue}'
      description: ''
    content.vb: Sub Configure(key As TKey, value As TValue)
  overload: PocoEmit.Collections.IConfigure`2.Configure*
  nameWithType.vb: IConfigure(Of TKey, TValue).Configure(TKey, TValue)
  fullName.vb: PocoEmit.Collections.IConfigure(Of TKey, TValue).Configure(TKey, TValue)
references:
- uid: PocoEmit.Collections
  commentId: N:PocoEmit.Collections
  href: PocoEmit.html
  name: PocoEmit.Collections
  nameWithType: PocoEmit.Collections
  fullName: PocoEmit.Collections
  spec.csharp:
  - uid: PocoEmit
    name: PocoEmit
    href: PocoEmit.html
  - name: .
  - uid: PocoEmit.Collections
    name: Collections
    href: PocoEmit.Collections.html
  spec.vb:
  - uid: PocoEmit
    name: PocoEmit
    href: PocoEmit.html
  - name: .
  - uid: PocoEmit.Collections
    name: Collections
    href: PocoEmit.Collections.html
- uid: PocoEmit.Collections.IConfigure`2.Configure*
  commentId: Overload:PocoEmit.Collections.IConfigure`2.Configure
  href: PocoEmit.Collections.IConfigure-2.html#PocoEmit_Collections_IConfigure_2_Configure__0__1_
  name: Configure
  nameWithType: IConfigure<TKey, TValue>.Configure
  fullName: PocoEmit.Collections.IConfigure<TKey, TValue>.Configure
  nameWithType.vb: IConfigure(Of TKey, TValue).Configure
  fullName.vb: PocoEmit.Collections.IConfigure(Of TKey, TValue).Configure
- uid: '{TKey}'
  commentId: '!:TKey'
  definition: TKey
  name: TKey
  nameWithType: TKey
  fullName: TKey
- uid: '{TValue}'
  commentId: '!:TValue'
  definition: TValue
  name: TValue
  nameWithType: TValue
  fullName: TValue
- uid: TKey
  name: TKey
  nameWithType: TKey
  fullName: TKey
- uid: TValue
  name: TValue
  nameWithType: TValue
  fullName: TValue
