### YamlMime:ManagedReference
items:
- uid: PocoEmit.Collections.ISettings`2
  commentId: T:PocoEmit.Collections.ISettings`2
  id: ISettings`2
  parent: PocoEmit.Collections
  children:
  - PocoEmit.Collections.ISettings`2.Set(`0,`1)
  - PocoEmit.Collections.ISettings`2.TryGetValue(`0,`1@)
  langs:
  - csharp
  - vb
  name: ISettings<TKey, TValue>
  nameWithType: ISettings<TKey, TValue>
  fullName: PocoEmit.Collections.ISettings<TKey, TValue>
  type: Interface
  source:
    remote:
      path: PocoEmit/Collections/ISettings~2.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: ISettings
    path: ../PocoEmit/Collections/ISettings~2.cs
    startLine: 7
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Collections
  summary: 配置设置
  example: []
  syntax:
    content: public interface ISettings<TKey, TValue>
    typeParameters:
    - id: TKey
      description: ''
    - id: TValue
      description: ''
    content.vb: Public Interface ISettings(Of TKey, TValue)
  nameWithType.vb: ISettings(Of TKey, TValue)
  fullName.vb: PocoEmit.Collections.ISettings(Of TKey, TValue)
  name.vb: ISettings(Of TKey, TValue)
- uid: PocoEmit.Collections.ISettings`2.TryGetValue(`0,`1@)
  commentId: M:PocoEmit.Collections.ISettings`2.TryGetValue(`0,`1@)
  id: TryGetValue(`0,`1@)
  parent: PocoEmit.Collections.ISettings`2
  langs:
  - csharp
  - vb
  name: TryGetValue(TKey, out TValue)
  nameWithType: ISettings<TKey, TValue>.TryGetValue(TKey, out TValue)
  fullName: PocoEmit.Collections.ISettings<TKey, TValue>.TryGetValue(TKey, out TValue)
  type: Method
  source:
    remote:
      path: PocoEmit/Collections/ISettings~2.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: TryGetValue
    path: ../PocoEmit/Collections/ISettings~2.cs
    startLine: 15
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Collections
  summary: 获取
  example: []
  syntax:
    content: bool TryGetValue(TKey key, out TValue value)
    parameters:
    - id: key
      type: '{TKey}'
      description: ''
    - id: value
      type: '{TValue}'
      description: ''
    return:
      type: System.Boolean
      description: ''
    content.vb: Function TryGetValue(key As TKey, value As TValue) As Boolean
  overload: PocoEmit.Collections.ISettings`2.TryGetValue*
  nameWithType.vb: ISettings(Of TKey, TValue).TryGetValue(TKey, TValue)
  fullName.vb: PocoEmit.Collections.ISettings(Of TKey, TValue).TryGetValue(TKey, TValue)
  name.vb: TryGetValue(TKey, TValue)
- uid: PocoEmit.Collections.ISettings`2.Set(`0,`1)
  commentId: M:PocoEmit.Collections.ISettings`2.Set(`0,`1)
  id: Set(`0,`1)
  parent: PocoEmit.Collections.ISettings`2
  langs:
  - csharp
  - vb
  name: Set(TKey, TValue)
  nameWithType: ISettings<TKey, TValue>.Set(TKey, TValue)
  fullName: PocoEmit.Collections.ISettings<TKey, TValue>.Set(TKey, TValue)
  type: Method
  source:
    remote:
      path: PocoEmit/Collections/ISettings~2.cs
      branch: main
      repo: https://github.com/donetsoftwork/MyEmit.git
    id: Set
    path: ../PocoEmit/Collections/ISettings~2.cs
    startLine: 21
  assemblies:
  - PocoEmit
  namespace: PocoEmit.Collections
  summary: 设置
  example: []
  syntax:
    content: void Set(TKey key, TValue value)
    parameters:
    - id: key
      type: '{TKey}'
      description: ''
    - id: value
      type: '{TValue}'
      description: ''
    content.vb: Sub [Set](key As TKey, value As TValue)
  overload: PocoEmit.Collections.ISettings`2.Set*
  nameWithType.vb: ISettings(Of TKey, TValue).Set(TKey, TValue)
  fullName.vb: PocoEmit.Collections.ISettings(Of TKey, TValue).Set(TKey, TValue)
references:
- uid: PocoEmit.Collections
  commentId: N:PocoEmit.Collections
  href: PocoEmit.html
  name: PocoEmit.Collections
  nameWithType: PocoEmit.Collections
  fullName: PocoEmit.Collections
  spec.csharp:
  - uid: PocoEmit
    name: PocoEmit
    href: PocoEmit.html
  - name: .
  - uid: PocoEmit.Collections
    name: Collections
    href: PocoEmit.Collections.html
  spec.vb:
  - uid: PocoEmit
    name: PocoEmit
    href: PocoEmit.html
  - name: .
  - uid: PocoEmit.Collections
    name: Collections
    href: PocoEmit.Collections.html
- uid: PocoEmit.Collections.ISettings`2.TryGetValue*
  commentId: Overload:PocoEmit.Collections.ISettings`2.TryGetValue
  href: PocoEmit.Collections.ISettings-2.html#PocoEmit_Collections_ISettings_2_TryGetValue__0__1__
  name: TryGetValue
  nameWithType: ISettings<TKey, TValue>.TryGetValue
  fullName: PocoEmit.Collections.ISettings<TKey, TValue>.TryGetValue
  nameWithType.vb: ISettings(Of TKey, TValue).TryGetValue
  fullName.vb: PocoEmit.Collections.ISettings(Of TKey, TValue).TryGetValue
- uid: '{TKey}'
  commentId: '!:TKey'
  definition: TKey
  name: TKey
  nameWithType: TKey
  fullName: TKey
- uid: '{TValue}'
  commentId: '!:TValue'
  definition: TValue
  name: TValue
  nameWithType: TValue
  fullName: TValue
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: TKey
  name: TKey
  nameWithType: TKey
  fullName: TKey
- uid: TValue
  name: TValue
  nameWithType: TValue
  fullName: TValue
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: PocoEmit.Collections.ISettings`2.Set*
  commentId: Overload:PocoEmit.Collections.ISettings`2.Set
  href: PocoEmit.Collections.ISettings-2.html#PocoEmit_Collections_ISettings_2_Set__0__1_
  name: Set
  nameWithType: ISettings<TKey, TValue>.Set
  fullName: PocoEmit.Collections.ISettings<TKey, TValue>.Set
  nameWithType.vb: ISettings(Of TKey, TValue).Set
  fullName.vb: PocoEmit.Collections.ISettings(Of TKey, TValue).Set
